# -*- coding: utf-8 -*-

# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


CATALOG_DATASET_ALIAS = "location"
CATALOG_SDFHLOAD_ALIAS = "sdfhload"
CATALOG_TARGET_STATE_ALIAS = "state"
CATALOG_PRIMARY_SPACE_VALUE_ALIAS = "space_primary"
CATALOG_PRIMARY_SPACE_UNIT_ALIAS = "space_type"
CATALOG_SPACE_UNIT_OPTIONS = ["K", "M", "REC", "CYL", "TRK"]

AUTO_START_WARM = "AUTOASIS"
AUTO_START_COLD = "AUTOCOLD"
AUTO_START_INIT = "AUTOINIT"

NEXT_START_EMERGENCY = "EMERGENCY"
NEXT_START_WARM = "WARM"
NEXT_START_COLD = "COLD"
NEXT_START_UNKNOWN = "UNKNOWN"

GLOBAL_CATALOG_PRIMARY_SPACE_VALUE_DEFAULT = 5
GLOBAL_CATALOG_SECONDARY_SPACE_VALUE_DEFAULT = 1
GLOBAL_CATALOG_SPACE_UNIT_DEFAULT = "M"
GLOBAL_CATALOG_TARGET_STATE_OPTIONS = ['absent', 'initial', 'cold', 'warm']
GLOBAL_CATALOG_RECORD_COUNT_DEFAULT = 4089
GLOBAL_CATALOG_RECORD_SIZE_DEFAULT = 32760
GLOBAL_CATALOG_CONTROL_INTERVAL_SIZE_DEFAULT = 32768

LOCAL_CATALOG_PRIMARY_SPACE_VALUE_DEFAULT = "200"
LOCAL_CATALOG_SECONDARY_SPACE_VALUE_DEFAULT = "5"
LOCAL_CATALOG_SPACE_UNIT_DEFAULT = "REC"
LOCAL_CATALOG_TARGET_STATE_ABSENT = 'absent'
LOCAL_CATALOG_TARGET_STATE_INITIAL = 'initial'
LOCAL_CATALOG_TARGET_STATE_OPTIONS = [LOCAL_CATALOG_TARGET_STATE_ABSENT,
                                      LOCAL_CATALOG_TARGET_STATE_INITIAL]
LOCAL_CATALOG_RECORD_COUNT_DEFAULT = 70
LOCAL_CATALOG_RECORD_SIZE_DEFAULT = 2041
LOCAL_CATALOG_CONTROL_INTERVAL_SIZE_DEFAULT = 2048
