# Copyright (c) IBM Corporation 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
###############################################################################
# This sample playbook demonstrates using various modules included in the
# Red Hat Ansible Certified Content for IBM Z core and IBM Z CICS collection.
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory cics-collection-sample-deploy-resource.yaml
#
# Notes:
#  This sample demonstrates various ways to perform tasks using Ansible z/OS
#  core modules. Each module has options available on how automation can be
#  controlled. This sample does not demonstrate all options, refer to
#  documentation or ansible-doc for those options.
#
#  When running this playbook, review the comments on how ths sample will
#  interact with your target, ensure you have the required authority and
#  permissions such as writing the the target directories or creating data sets.
#
#  Additional facts for this playbook can be configured to override the defaults
#  by reviewing the "Fact setting" section of this playbook, for example,
#  `destination`.
#
# Requirements:
#   IBM z/OS core collection 1.2.0-beta.1 or later
#   IBM z/OS CICS collection 1.0.0 or later
#   ZOAU 1.0.1 or later
#
# Configure:
#   cmci_host - this is host system that host the your region.
#   cmci_port - the CMCI port configured in your cics region.
#   cmci_context - the CICS region's applid.
#   BUNDLE_DIR - the bundle directory to store the bundle files
#   app_name - the application name in this sample
###############################################################################

---
- name:  CICS resources deployment
  hosts: zos-workers
  collections:
   - ibm.ibm_zos_core
   - ibm.ibm_zos_cics
  gather_facts: false
  vars:
    cmci_host: "ibmhost.com"
    cmci_port: "1000"
    cmci_context: "CICSA"
    BUNDLE_DIR: "/tmp/"
    app_name: "PONG"
  environment: "{{ environment_vars }}"

  tasks:
  - name: disable a library in a CICS region
    ibm.ibm_zos_cics.cics_cmci:
      cmci_host: '{{ cmci_host }}'
      cmci_port: '{{ cmci_port }}'
      context: '{{ cmci_context }}'
      option: 'update'
      resource: 
        type: CICSLIBRARY
        attributes:
          Enablestatus: disabled
      criteria: "NAME={{ app_name }}"
    delegate_to: localhost
    register: result

  - name: Response for check if library was successfully disabled
    debug:
      msg: "{{ result }}"

  - name: delete a library in a CICS region
    ibm.ibm_zos_cics.cics_cmci:
      cmci_host: '{{ cmci_host }}'
      cmci_port: '{{ cmci_port }}'
      context: '{{ cmci_context }}'
      option: 'delete'
      resource: 
        type: CICSLIBRARY
      criteria: "NAME={{ app_name }}"
    delegate_to: localhost
    register: result

  - name: Response for check if library was successfully deleted
    debug:
      msg: "{{ result }}"

  - name: delete a library definition in a CICS region
    ibm.ibm_zos_cics.cics_cmci:
      cmci_host: '{{ cmci_host }}'
      cmci_port: '{{ cmci_port }}'
      context: '{{ cmci_context }}'
      option: 'delete'
      resource:
        type: CICSDefinitionLIBRARY
      criteria: "NAME={{ app_name }}"
      parameter: 'CSDGROUP(TSTGRP)'
    delegate_to: localhost
    register: result

  - name: Response for check if library definition was successfully deleted
    debug:
      msg: "{{ result }}"

  - name: disable a bundle in a CICS region
    ibm.ibm_zos_cics.cics_cmci:
      cmci_host: '{{ cmci_host }}'
      cmci_port: '{{ cmci_port }}'
      context: '{{ cmci_context }}'
      option: 'update'
      resource: 
        type: CICSBundle
        attributes:
          Enablestatus: disabled
      criteria: "NAME={{ app_name }}"
    delegate_to: localhost
    register: result

  - name: Response for check if bundle was successfully disabled
    debug:
      msg: "{{ result }}"

  - name: delete a bundle in a CICS region
    ibm.ibm_zos_cics.cics_cmci:
      cmci_host: '{{ cmci_host }}'
      cmci_port: '{{ cmci_port }}'
      context: '{{ cmci_context }}'
      option: 'delete'
      resource: 
        type: CICSBundle
      criteria: "NAME={{ app_name }}"
    delegate_to: localhost
    register: result


  - name: delete a bundle definition in a CICS region
    ibm.ibm_zos_cics.cics_cmci:
      cmci_host: '{{ cmci_host }}'
      cmci_port: '{{ cmci_port }}'
      context: '{{ cmci_context }}'
      option: 'delete'
      resource: 
        type: CICSDefinitionBundle
      criteria: "NAME={{ app_name }}"
      parameter: CSDGROUP(TSTGRP)
    delegate_to: localhost
    register: result

  - name: Delete PONG zip
    file:
      path: "{{ BUNDLE_DIR }}"
      state: absent

